- name: Install docker pre-requisities
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3
      - python3-pip
      - python3-setuptools
    update_cache: yes
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Update apt and install docker-ce package
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
    state: present

- name: "Add SSH user to the docker group"
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

#- name: Install Python Docker module
#  pip:
#    name:
#      - docker